/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CauponCard: typeof import('./src/components/common/CauponCard.vue')['default']
    CustomerIndex: typeof import('./src/components/Customer/CustomerIndex.vue')['default']
    ManageIndex: typeof import('./src/components/ProductManagement/ManageIndex.vue')['default']
    ManageItem: typeof import('./src/components/ProductManagement/ManageItem.vue')['default']
    ManageProduct: typeof import('./src/components/ProductManagement/ManageProduct.vue')['default']
    OrderList: typeof import('./src/components/Orders/OrderList.vue')['default']
    ProductDetail: typeof import('./src/components/ProductInfo/ProductDetail.vue')['default']
    ProductList: typeof import('./src/components/ProductInfo/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsView: typeof import('./src/components/Statistics/StatisticsView.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCouponCell: typeof import('vant/es')['CouponCell']
    VanCouponList: typeof import('vant/es')['CouponList']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanTag: typeof import('vant/es')['Tag']
    VanUploader: typeof import('vant/es')['Uploader']
    Verification: typeof import('./src/components/common/Verification.vue')['default']
  }
}
